Repository internxt/sdk, pull requests merged in 2024-07, with the labels that each got.

#211 [PB-2242]: chore/update workspaces endpoints
  package.json
  src/drive/share/index.ts
  src/drive/share/types.ts
  src/drive/storage/index.ts
  src/drive/trash/index.ts
  src/network/index.ts
  src/shared/headers/index.ts
  src/shared/types/apiConnection.ts
  src/workspaces/index.test.ts
  src/workspaces/index.ts
  src/workspaces/types.ts
Labels: enhancement

#215 [_]: Added update name of items with uuid
  package.json
  src/drive/storage/index.ts
Labels: enhancement

#216 Chore: B2B expand methods
  package.json
  src/drive/payments/index.ts
  src/drive/payments/types.ts
Labels: enhancement

#217 [_]: feature/Added getFolderTree call
  package.json
  src/drive/storage/index.ts
  src/drive/storage/types.ts
Labels: enhancement

#218 [_]: Delete trash items payload type changed
  package.json
  src/drive/trash/index.ts
  src/drive/trash/types.ts
Labels: enhancement

#219 [PB-2367] feature/Use correct member usage endpoint
  package.json
  src/workspaces/index.test.ts
  src/workspaces/index.ts
  src/workspaces/types.ts
Labels: enhancement

#224 [_]: Bump package version
  package.json
Labels: enhancement

#227 [PB-2398] bugfix/Added resources token header for make work endpoint in shared folders
  package.json
  src/drive/storage/index.ts
  src/workspaces/index.ts
Labels: bug, enhancement

#228 [BR-249]: bugfix/Add rootFolderUuid field in user interface
  package.json
  src/shared/types/userSettings.ts
Labels: bug
